// model for widget
// model for widget
class QuoteWidget {
  final String id;
  final String quote; // The one quote currently visible on the home screen
  final List<String> quotes; // The full list of 10 quotes generated by AI
  final String topic; // The topic you typed in (e.g., "Success")
  final String
  frequency; // How often it rotates ('none', 'one hour', 'one day')
  final int currentIndex; // Which of the 10 quotes is currently being shown
  final String widgetName; // 'StikiWidgetLight' or 'StikiWidgetDark'
  final DateTime createdAt;
  final DateTime lastUpdated; // New: Tracks when we last rotated or edited

  QuoteWidget({
    required this.id,
    required this.quote,
    required this.quotes,
    required this.topic,
    required this.frequency,
    required this.currentIndex,
    required this.widgetName,
    required this.createdAt,
    required this.lastUpdated,
  });

  // This converts our object into a Map so it can be saved in SharedPreferences
  Map<String, dynamic> toJson() => {
    'id': id,
    'quote': quote,
    'quotes': quotes,
    'topic': topic,
    'frequency': frequency,
    'currentIndex': currentIndex,
    'widgetName': widgetName,
    'createdAt': createdAt.toIso8601String(),
    'lastUpdated': lastUpdated.toIso8601String(),
  };

  // This creates the object back from the map when we read it from storage
  factory QuoteWidget.fromJson(Map<String, dynamic> json) {
    final createdAt = DateTime.parse(json['createdAt'] as String);
    return QuoteWidget(
      id: json['id'] as String,
      quote: json['quote'] as String,
      quotes: List<String>.from(json['quotes'] ?? []),
      topic: json['topic'] ?? '',
      frequency: json['frequency'] ?? 'daily',
      currentIndex: json['currentIndex'] ?? 0,
      widgetName: json['widgetName'] ?? 'StikiWidgetLight',
      createdAt: createdAt,
      // Migration: Use createdAt if lastUpdated doesn't exist yet
      lastUpdated: json['lastUpdated'] != null
          ? DateTime.parse(json['lastUpdated'] as String)
          : createdAt,
    );
  }
}
